feat: retry deleteByIds operation
because it sometimes throws this:
Error: 10 ABORTED: too much contention on these datastore entities. please try again.

saveBatch and getByIds were already covered with pRetry,
now deleteByIds is covered too